window.tsCatalog = [
  { id: 1, name: "Betty Crocker Indulgent Chocolate Fudge Icing 400g", category: "Cooking Chocolate Retail", size: "4 x 400g", supplier: "Bookers", price: 9.99, vatRate: 0 },
  { id: 2, name: "Billington's Dark Brown Soft Natural Unrefined Cane Sugar 500g", category: "Brown Sugar Retail", size: "10 x 500g", supplier: "Bookers", price: 11.79, vatRate: 0 },
  { id: 3, name: "Billington's Light Brown Soft Natural Unrefined Cane Sugar 3kg", category: "Sugar Demerara & Brown", size: "1 x 3kg", supplier: "Bookers", price: 12.99, vatRate: 0 },
  { id: 4, name: "Billington's Light Brown Soft Natural Unrefined Cane Sugar 500g", category: "Brown Sugar Retail", size: "10 x 500g", supplier: "Bookers", price: 11.45, vatRate: 0 },
  { id: 5, name: "Biscoff Biscuit Crumbs 750g", category: "Baking Cake Decoration", size: "8 x 750g", supplier: "Bookers", price: 33.49, vatRate: 0 },
  { id: 6, name: "Cadbury Drinking Hot Chocolate Cocoa Powder Large Tub 2KG", category: "Hot Chocolate & Cocoa", size: "1 x 2kg", supplier: "Bookers", price: 16.15, vatRate: 0 },
  { id: 7, name: "CaterPro 100 Wooden Dessert Spoons", category: "Disposable Cutlery & Accessories", size: "10 x 100s", supplier: "Bookers", price: 14.99, vatRate: 20 },
  { id: 8, name: "CaterPro 100 Wooden Forks", category: "Disposable Cutlery & Accessories", size: "10 x 100s", supplier: "Bookers", price: 14.99, vatRate: 20 },
  { id: 9, name: "Chef's Essentials Chopped Tomatoes in Tomato Juice 2.5kg", category: "Canned Tomatoes & Pizza Toppings Catering", size: "6 x 2.5kg", supplier: "Bookers", price: 16.99, vatRate: 0 },
  { id: 10, name: "Chef's Larder Lightly Salted Tortilla Chips 454g", category: "Crisps & Snacks Sharing", size: "6 x 454g", supplier: "Bookers", price: 11.49, vatRate: 0 },
  { id: 11, name: "Chef's Larder Salt 6kg", category: "Salt", size: "1 x 6kg", supplier: "Bookers", price: 7.99, vatRate: 0 },
  { id: 12, name: "Chef's Larder White Wine Vinegar 2 Litres", category: "Vinegar, Glaze & Cooking Wine", size: "1 x 2ltr", supplier: "Bookers", price: 3.79, vatRate: 0 },
  { id: 13, name: "Chef's Menu Garlic Powder 500g", category: "Seasonings & Garlic Catering", size: "1 x 500g", supplier: "Bookers", price: 8.49, vatRate: 0 },
  { id: 14, name: "Chef's Menu Cayenne Pepper 460g", category: "Pepper Catering", size: "1 x 460g", supplier: "Bookers", price: 5.99, vatRate: 0 },
  { id: 15, name: "Chef's Menu Chipotle Sauce 1 litre", category: "Condiments Other Sauces", size: "6 x 1ltr", supplier: "Bookers", price: 14.99, vatRate: 0 },
  { id: 16, name: "Chef's Menu Ground Black Pepper 500g", category: "Pepper Catering", size: "1 x 500g", supplier: "Bookers", price: 13.99, vatRate: 0 },
  { id: 17, name: "Chef's Menu Ground Sweet Cinnamon 430g", category: "Seasonings & Garlic Catering", size: "1 x 430g", supplier: "Bookers", price: 5.49, vatRate: 0 },
  { id: 18, name: "Chef's Menu Onion Powder 480g", category: "Seasonings & Garlic Catering", size: "1 x 480g", supplier: "Bookers", price: 5.89, vatRate: 0 },
  { id: 19, name: "Chef's Menu Salsa 1 litre", category: "Condiments Other Sauces", size: "1 x 1ltr", supplier: "Bookers", price: 2.99, vatRate: 0 },
  { id: 20, name: "Chef's Menu Smoked Paprika 430g", category: "Seasonings & Garlic Catering", size: "1 x 430g", supplier: "Bookers", price: 5.49, vatRate: 0 },
  { id: 21, name: "Chef's Menu Turmeric 500g", category: "Seasonings & Garlic Catering", size: "1 x 500g", supplier: "Bookers", price: 4.89, vatRate: 0 },
  { id: 22, name: "Chefs Essentials Pure Vegetable Oil 20L", category: "Cooking Oil & Fat", size: "1 x 20ltr", supplier: "Bookers", price: 26.99, vatRate: 0 },
  { id: 23, name: "Clean Pro + Fast Acting Antibacterial Cleaner and Degreaser 5 Litres", category: "Professional General Cleaning", size: "1 x 5ltr", supplier: "Bookers", price: 8.49, vatRate: 20 },
  { id: 24, name: "Clean Pro 50 Heavy Duty Refuse Sacks 120 Litres", category: "Bin Bags & Food Wrap", size: "1 x 50s", supplier: "Bookers", price: 13.29, vatRate: 20 },
  { id: 25, name: "Clean Pro Bleach 5 Litres", category: "Toilet, Bathroom & Bleach", size: "2 x 5ltr", supplier: "Bookers", price: 5.99, vatRate: 20 },
  { id: 26, name: "Clean Pro Lemon Washing Up Liquid 5 Litres", category: "Kitchen Dishwashing", size: "2 x 5ltr", supplier: "Bookers", price: 8.49, vatRate: 20 },
  { id: 27, name: "Clean Pro Pine Disinfectant 5 Litres", category: "Professional General Cleaning", size: "2 x 5ltr", supplier: "Bookers", price: 6.99, vatRate: 20 },
  { id: 28, name: "Coke Diet Bottle 500ML", category: "Carbonates", size: "24 x 500ml", supplier: "Bookers", price: 16.99, vatRate: 20 },
  { id: 29, name: "Coke Zero Bottle 500ml", category: "Carbonates", size: "24 x 500ml", supplier: "Bookers", price: 16.99, vatRate: 20 },
  { id: 30, name: "De Cecco Penne Rigate No 41 Pasta 3kg", category: "Dry Pasta & Noodles", size: "1 x 3kg", supplier: "Bookers", price: 8.85, vatRate: 0 },
  { id: 31, name: "De Cecco Spaghetti No.12 Pasta 3kg", category: "Dry Pasta & Noodles", size: "1 x 3kg", supplier: "Bookers", price: 8.85, vatRate: 0 },
  { id: 32, name: "Discovery Tortilla Wrap 10 1/2inch", category: "Naans & Flatbreads", size: "4 x 18s", supplier: "Bookers", price: 21.65, vatRate: 0 },
  { id: 33, name: "Dispo 50 Bagasse Hinged Meal Boxes 9x6inch", category: "Takeaway Containers", size: "5 x 50s", supplier: "Bookers", price: 34.99, vatRate: 20 },
  { id: 34, name: "Dispo 50 Bagasse Hinged Meal Boxes 9x9inch", category: "Takeaway Containers", size: "4 x 50s", supplier: "Bookers", price: 41.99, vatRate: 20 },
  { id: 35, name: "Elmlea Double Alternative to Cream 284ml", category: "Cream & Substitutes Retail", size: "6 x 284ml", supplier: "Bookers", price: 7.79, vatRate: 0 },
  { id: 36, name: "Elmlea Single Alternative to Cream 284ml", category: "Cream & Substitutes Retail", size: "6 x 284ml", supplier: "Bookers", price: 5.75, vatRate: 0 },
  { id: 37, name: "Fanta Orange Bottle 500ML", category: "Carbonates", size: "24 x 500ml", supplier: "Bookers", price: 16.99, vatRate: 20 },
  { id: 38, name: "Fruittella Juicy Chews Sweets Multipack 4 x 41g", category: "Jellies, Chews & Sweets Retail", size: "12 x 4pks", supplier: "Bookers", price: 19.99, vatRate: 20 },
  { id: 39, name: "Gala Apples 6 Pack", category: "Apples", size: "1 x 6pks", supplier: "Bookers", price: 1.69, vatRate: 0 },
  { id: 40, name: "Green Giant Naturally Sweet Sweetcorn 340g", category: "Canned Vegetables", size: "12 x 340g", supplier: "Bookers", price: 16.99, vatRate: 0 },
  { id: 41, name: "Hardys Stamp Chardonnay Semillon Wine 75cl", category: "Still White Wine", size: "6 x 75cl", supplier: "Bookers", price: 34.74, vatRate: 20 },
  { id: 42, name: "Hardys Stamp Shiraz Cabernet Wine 75cl", category: "Still Red Wine", size: "6 x 75cl", supplier: "Bookers", price: 34.74, vatRate: 20 },
  { id: 43, name: "Haribo Jelly Beans Sweets Share Bag 140g", category: "Jellies, Chews & Sweets Retail", size: "12 x 140g", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 44, name: "Haribo Starmix Sweets Share Bag 140g", category: "Jellies, Chews & Sweets Retail", size: "12 x 140g", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 45, name: "Haribo Supermix Sweets Share Bag 140g", category: "Jellies, Chews & Sweets Retail", size: "12 x 140g", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 46, name: "Haribo Tangfastics Sweets Share Bag 140g", category: "Jellies, Chews & Sweets Retail", size: "12 x 140g", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 47, name: "Hellmann's Real Mayonnaise 2 Litres", category: "Condiments Mayonnaise", size: "1 x 2ltr", supplier: "Bookers", price: 13.99, vatRate: 0 },
  { id: 48, name: "Highland Spring Sparkling Water Bottle 500ML", category: "Bottled Water Sparkling", size: "24 x 500ml", supplier: "Bookers", price: 8.49, vatRate: 20 },
  { id: 49, name: "Highland Spring Still Water Bottle 500ML", category: "Bottled Water Still", size: "24 x 500ml", supplier: "Bookers", price: 8.49, vatRate: 20 },
  { id: 50, name: "Kellogg's Coco Pops Cereal 480g", category: "Cereals Retail", size: "12 x 480g", supplier: "Bookers", price: 42.99, vatRate: 0 },
  { id: 51, name: "Kellogg's Corn Flakes Cereal 720g", category: "Cereals Retail", size: "6 x 720g", supplier: "Bookers", price: 19.99, vatRate: 0 },
  { id: 52, name: "Kellogg's Crunchy Nut Cereal 500g", category: "Cereals Retail", size: "10 x 500g", supplier: "Bookers", price: 34.49, vatRate: 0 },
  { id: 53, name: "Kellogg's Frosties Cereal 500g", category: "Cereals Retail", size: "10 x 500g", supplier: "Bookers", price: 35.49, vatRate: 0 },
  { id: 54, name: "Ken's Premium 100 Paper Portion Pots 2oz", category: "Food Preparation & Presentation", size: "10 x 100s", supplier: "Bookers", price: 34.99, vatRate: 20 },
  { id: 55, name: "Ken's Premium 100 Paper Portion Pots 4oz", category: "Food Preparation & Presentation", size: "10 x 100s", supplier: "Bookers", price: 44.99, vatRate: 20 },
  { id: 56, name: "Kenco Smooth Instant Coffee 750g", category: "Coffee Catering", size: "1 x 750g", supplier: "Bookers", price: 29.99, vatRate: 0 },
  { id: 57, name: "Kenco Decaffeinated Instant Coffee 500g", category: "Coffee Catering", size: "1 x 500g", supplier: "Bookers", price: 24.99, vatRate: 0 },
  { id: 58, name: "KTC Pure Sunflower Oil 5 Litres", category: "Cooking Oil & Fat", size: "4 x 5ltr", supplier: "Bookers", price: 29.99, vatRate: 0 },
  { id: 59, name: "Lichfields Fairtrade White Sugar Sticks", category: "Sugar Portions", size: "1 x 1000s", supplier: "Bookers", price: 10.99, vatRate: 0 },
  { id: 60, name: "Lichfields Fairtrade Brown Sugar Sticks", category: "Sugar Portions", size: "1 x 1000s", supplier: "Bookers", price: 11.49, vatRate: 0 },
  { id: 61, name: "Lion Dairy Single Cream 1 Litre", category: "Cream & Substitutes Catering", size: "12 x 1ltr", supplier: "Bookers", price: 35.88, vatRate: 0 },
  { id: 62, name: "Lion Dairy Double Cream 1 Litre", category: "Cream & Substitutes Catering", size: "12 x 1ltr", supplier: "Bookers", price: 47.88, vatRate: 0 },
  { id: 63, name: "Lotus Biscoff Biscuits 300g", category: "Biscuits Retail", size: "10 x 300g", supplier: "Bookers", price: 16.99, vatRate: 0 },
  { id: 64, name: "Lotus Biscoff Spread 400g", category: "Jams & Sweet Spreads", size: "8 x 400g", supplier: "Bookers", price: 21.49, vatRate: 0 },
  { id: 65, name: "Lurpak Slightly Salted Spreadable 500g", category: "Butter & Margarine Retail", size: "6 x 500g", supplier: "Bookers", price: 29.94, vatRate: 0 },
  { id: 66, name: "Lurpak Unsalted Butter 250g", category: "Butter & Margarine Retail", size: "20 x 250g", supplier: "Bookers", price: 43.80, vatRate: 0 },
  { id: 67, name: "Maldon Sea Salt Flakes 250g", category: "Salt", size: "12 x 250g", supplier: "Bookers", price: 28.68, vatRate: 0 },
  { id: 68, name: "McCain Signatures Gastro Chunky Chips 2.27kg", category: "Frozen Chips Catering", size: "4 x 2.27kg", supplier: "Bookers", price: 18.99, vatRate: 0 },
  { id: 69, name: "McCain SureCrisp Skin-On Fries 2.27kg", category: "Frozen Chips Catering", size: "4 x 2.27kg", supplier: "Bookers", price: 17.99, vatRate: 0 },
  { id: 70, name: "Milka Alpine Milk Chocolate Bar 100g", category: "Chocolate Blocks", size: "22 x 100g", supplier: "Bookers", price: 23.98, vatRate: 20 },
  { id: 71, name: "Milkybar White Chocolate Buttons Share Bag 94g", category: "Chocolate Bags", size: "12 x 94g", supplier: "Bookers", price: 14.99, vatRate: 20 },
  { id: 72, name: "Monster Energy Drink 500ml", category: "Energy Drinks", size: "12 x 500ml", supplier: "Bookers", price: 11.99, vatRate: 20 },
  { id: 73, name: "Monster Mango Loco Energy Drink 500ml", category: "Energy Drinks", size: "12 x 500ml", supplier: "Bookers", price: 11.99, vatRate: 20 },
  { id: 74, name: "Monster Pipeline Punch Energy Drink 500ml", category: "Energy Drinks", size: "12 x 500ml", supplier: "Bookers", price: 11.99, vatRate: 20 },
  { id: 75, name: "Mutti Polpa Finely Chopped Tomatoes 400g", category: "Canned Tomatoes Retail", size: "12 x 400g", supplier: "Bookers", price: 14.99, vatRate: 0 },
  { id: 76, name: "Nescafé Original Instant Coffee 750g", category: "Coffee Catering", size: "1 x 750g", supplier: "Bookers", price: 34.99, vatRate: 0 },
  { id: 77, name: "Nestlé Carnation Condensed Milk 397g", category: "Baking Cake Decoration", size: "12 x 397g", supplier: "Bookers", price: 22.68, vatRate: 0 },
  { id: 78, name: "Nestlé Carnation Evaporated Milk 410g", category: "Baking Cake Decoration", size: "12 x 410g", supplier: "Bookers", price: 19.08, vatRate: 0 },
  { id: 79, name: "Nutella Hazelnut Chocolate Spread 1kg", category: "Jams & Sweet Spreads", size: "1 x 1kg", supplier: "Bookers", price: 6.99, vatRate: 0 },
  { id: 80, name: "Oreo Vanilla Sandwich Biscuits 154g", category: "Biscuits Retail", size: "16 x 154g", supplier: "Bookers", price: 15.84, vatRate: 0 },
  { id: 81, name: "PG Tips Pyramid Tea Bags 1150s", category: "Tea Catering", size: "1 x 1150s", supplier: "Bookers", price: 21.99, vatRate: 0 },
  { id: 82, name: "Pringles Original Crisps 165g", category: "Crisps & Snacks Sharing", size: "19 x 165g", supplier: "Bookers", price: 29.45, vatRate: 20 },
  { id: 83, name: "Pringles Sour Cream & Onion Crisps 165g", category: "Crisps & Snacks Sharing", size: "19 x 165g", supplier: "Bookers", price: 29.45, vatRate: 20 },
  { id: 84, name: "Pringles Texas BBQ Sauce Crisps 165g", category: "Crisps & Snacks Sharing", size: "19 x 165g", supplier: "Bookers", price: 29.45, vatRate: 20 },
  { id: 85, name: "Quaker Oat So Simple Original Porridge Sachets 10x27g", category: "Cereals Retail", size: "6 x 10pks", supplier: "Bookers", price: 16.50, vatRate: 0 },
  { id: 86, name: "Red Bull Energy Drink 250ml", category: "Energy Drinks", size: "24 x 250ml", supplier: "Bookers", price: 24.99, vatRate: 20 },
  { id: 87, name: "Red Bull Sugarfree Energy Drink 250ml", category: "Energy Drinks", size: "24 x 250ml", supplier: "Bookers", price: 24.99, vatRate: 20 },
  { id: 88, name: "Ritz Crackers 200g", category: "Crackers & Crispbreads", size: "12 x 200g", supplier: "Bookers", price: 18.00, vatRate: 0 },
  { id: 89, name: "Robinsons Apple & Blackcurrant Squash 1 Litre", category: "Squash & Cordial Retail", size: "12 x 1ltr", supplier: "Bookers", price: 16.68, vatRate: 20 },
  { id: 90, name: "Robinsons Orange Squash 1 Litre", category: "Squash & Cordial Retail", size: "12 x 1ltr", supplier: "Bookers", price: 16.68, vatRate: 20 },
  { id: 91, name: "Rowntree's Fruit Pastilles Sweets Share Bag 143g", category: "Jellies, Chews & Sweets Retail", size: "12 x 143g", supplier: "Bookers", price: 13.08, vatRate: 20 },
  { id: 92, name: "San Pellegrino Limonata Sparkling Lemon Drink 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 14.99, vatRate: 20 },
  { id: 93, name: "San Pellegrino Aranciata Sparkling Orange Drink 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 14.99, vatRate: 20 },
  { id: 94, name: "San Pellegrino Sparkling Water 750ml", category: "Bottled Water Sparkling", size: "12 x 750ml", supplier: "Bookers", price: 15.48, vatRate: 20 },
  { id: 95, name: "Schwartz Black Peppercorns 380g", category: "Pepper Catering", size: "1 x 380g", supplier: "Bookers", price: 14.99, vatRate: 0 },
  { id: 96, name: "Schwartz Garlic Granules 320g", category: "Seasonings & Garlic Catering", size: "1 x 320g", supplier: "Bookers", price: 9.99, vatRate: 0 },
  { id: 97, name: "Schwartz Ground Cumin 400g", category: "Seasonings & Garlic Catering", size: "1 x 400g", supplier: "Bookers", price: 9.49, vatRate: 0 },
  { id: 98, name: "Schwartz Mixed Herbs 100g", category: "Herbs Catering", size: "1 x 100g", supplier: "Bookers", price: 4.49, vatRate: 0 },
  { id: 99, name: "Schwartz Oregano 120g", category: "Herbs Catering", size: "1 x 120g", supplier: "Bookers", price: 6.49, vatRate: 0 },
  { id: 100, name: "Schweppes Lemonade 2 Litres", category: "Mixers", size: "6 x 2ltr", supplier: "Bookers", price: 10.50, vatRate: 20 },
  { id: 101, name: "Schweppes Tonic Water 1 Litre", category: "Mixers", size: "12 x 1ltr", supplier: "Bookers", price: 13.80, vatRate: 20 },
  { id: 102, name: "Sharwood's Mango Chutney 2.27kg", category: "Condiments Other Sauces", size: "2 x 2.27kg", supplier: "Bookers", price: 19.98, vatRate: 0 },
  { id: 103, name: "Silver Spoon Caster Sugar 2kg", category: "White Sugar Retail", size: "6 x 2kg", supplier: "Bookers", price: 16.14, vatRate: 0 },
  { id: 104, name: "Silver Spoon Granulated Sugar 5kg", category: "Sugar Granulated", size: "2 x 5kg", supplier: "Bookers", price: 10.98, vatRate: 0 },
  { id: 105, name: "Silver Spoon Icing Sugar 500g", category: "White Sugar Retail", size: "10 x 500g", supplier: "Bookers", price: 11.50, vatRate: 0 },
  { id: 106, name: "Skippy Extra Crunchy Peanut Butter 340g", category: "Jams & Sweet Spreads", size: "6 x 340g", supplier: "Bookers", price: 14.34, vatRate: 0 },
  { id: 107, name: "Skippy Smooth Peanut Butter 340g", category: "Jams & Sweet Spreads", size: "6 x 340g", supplier: "Bookers", price: 14.34, vatRate: 0 },
  { id: 108, name: "Tilda Easy Cook Basmati Rice 5kg", category: "Rice Catering", size: "1 x 5kg", supplier: "Bookers", price: 14.99, vatRate: 0 },
  { id: 109, name: "Tilda Pure Basmati Rice 10kg", category: "Rice Catering", size: "1 x 10kg", supplier: "Bookers", price: 29.99, vatRate: 0 },
  { id: 110, name: "Tiptree Strawberry Conserve 340g", category: "Jams & Sweet Spreads", size: "6 x 340g", supplier: "Bookers", price: 16.74, vatRate: 0 },
  { id: 111, name: "Tropicana Orange Juice with Bits 850ml", category: "Fruit Juice Retail", size: "6 x 850ml", supplier: "Bookers", price: 16.74, vatRate: 20 },
  { id: 112, name: "Tropicana Smooth Orange Juice 850ml", category: "Fruit Juice Retail", size: "6 x 850ml", supplier: "Bookers", price: 16.74, vatRate: 20 },
  { id: 113, name: "Twinings English Breakfast Tea Bags 100s", category: "Tea Retail", size: "4 x 100s", supplier: "Bookers", price: 21.96, vatRate: 0 },
  { id: 114, name: "Twinings Earl Grey Tea Bags 100s", category: "Tea Retail", size: "4 x 100s", supplier: "Bookers", price: 23.96, vatRate: 0 },
  { id: 115, name: "Twinings Peppermint Tea Bags 50s", category: "Tea Retail", size: "4 x 50s", supplier: "Bookers", price: 14.36, vatRate: 0 },
  { id: 116, name: "Typhoo One Cup Tea Bags 1100s", category: "Tea Catering", size: "1 x 1100s", supplier: "Bookers", price: 15.99, vatRate: 0 },
  { id: 117, name: "Uncle Ben's Long Grain Rice 5kg", category: "Rice Catering", size: "1 x 5kg", supplier: "Bookers", price: 12.99, vatRate: 0 },
  { id: 118, name: "Vegeta Vegetable Seasoning 1kg", category: "Seasonings & Garlic Catering", size: "6 x 1kg", supplier: "Bookers", price: 35.94, vatRate: 0 },
  { id: 119, name: "Volvic Touch of Fruit Sugar Free Strawberry Water 1.5 Litres", category: "Flavoured Water", size: "6 x 1.5ltr", supplier: "Bookers", price: 5.94, vatRate: 20 },
  { id: 120, name: "Walkers Cheese & Onion Crisps 32.5g", category: "Crisps & Snacks Standard", size: "32 x 32.5g", supplier: "Bookers", price: 22.08, vatRate: 20 },
  { id: 121, name: "Walkers Ready Salted Crisps 32.5g", category: "Crisps & Snacks Standard", size: "32 x 32.5g", supplier: "Bookers", price: 22.08, vatRate: 20 },
  { id: 122, name: "Walkers Salt & Vinegar Crisps 32.5g", category: "Crisps & Snacks Standard", size: "32 x 32.5g", supplier: "Bookers", price: 22.08, vatRate: 20 },
  { id: 123, name: "Werther's Original Butter Candies 135g", category: "Jellies, Chews & Sweets Retail", size: "12 x 135g", supplier: "Bookers", price: 13.08, vatRate: 20 },
  { id: 124, name: "Wrigley's Extra Peppermint Chewing Gum 14 Pellets", category: "Mints & Gum", size: "30 x 14s", supplier: "Bookers", price: 17.70, vatRate: 20 },
  { id: 125, name: "Wrigley's Extra Spearmint Chewing Gum 14 Pellets", category: "Mints & Gum", size: "30 x 14s", supplier: "Bookers", price: 17.70, vatRate: 20 },
  { id: 126, name: "Yeo Valley Organic Natural Yogurt 450g", category: "Yogurt Retail", size: "6 x 450g", supplier: "Bookers", price: 10.74, vatRate: 0 },
  { id: 127, name: "Yorkshire Tea Bags 1040s", category: "Tea Catering", size: "1 x 1040s", supplier: "Bookers", price: 24.99, vatRate: 0 },
  { id: 128, name: "Coke Diet Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 11.49, vatRate: 20 },
  { id: 129, name: "Coke Zero Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 11.49, vatRate: 20 },
  { id: 130, name: "Coca Cola Classic Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 131, name: "Fanta Orange Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 11.49, vatRate: 20 },
  { id: 132, name: "Fanta Lemon Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 11.49, vatRate: 20 },
  { id: 133, name: "Sprite Zero Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 11.49, vatRate: 20 },
  { id: 134, name: "7UP Free Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 9.99, vatRate: 20 },
  { id: 135, name: "Pepsi Max Can 330ml", category: "Carbonates", size: "24 x 330ml", supplier: "Bookers", price: 9.99, vatRate: 20 },
  { id: 136, name: "Lipton Ice Tea Peach 500ml", category: "Juices & Teas", size: "12 x 500ml", supplier: "Bookers", price: 10.99, vatRate: 20 },
  { id: 137, name: "Lipton Ice Tea Lemon 500ml", category: "Juices & Teas", size: "12 x 500ml", supplier: "Bookers", price: 10.99, vatRate: 20 },
  { id: 138, name: "Oasis Citrus Punch 500ml", category: "Juices & Teas", size: "12 x 500ml", supplier: "Bookers", price: 11.99, vatRate: 20 },
  { id: 139, name: "Oasis Summer Fruits 500ml", category: "Juices & Teas", size: "12 x 500ml", supplier: "Bookers", price: 11.99, vatRate: 20 },
  { id: 140, name: "Capri-Sun Orange 330ml", category: "Juices", size: "15 x 330ml", supplier: "Bookers", price: 12.99, vatRate: 20 },
  { id: 141, name: "Fruit Shoot Apple & Blackcurrant 200ml", category: "Juices", size: "24 x 200ml", supplier: "Bookers", price: 10.99, vatRate: 20 },
  { id: 142, name: "Fruit Shoot Orange 200ml", category: "Juices", size: "24 x 200ml", supplier: "Bookers", price: 10.99, vatRate: 20 }
];
